# CloudFormation Script
# Project: UdacityProject2
# Created by: Sasho Petrovski

# Web application script
Description:
  < Sasho Petrovski
  Udacity Project 2
  Website Application

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names.
    Type: String
    
  ProjectName:
    Description: The project name you're working on.
    Type: String

  EC2AccessKeyPair:
    Description: The Key Pair name used to access the EC2 via SSH.
    Type: String

  EC2InstanceProfileRole:
    Description: IAM Role profile to be used when launching an EC2 Instance.
    Type: String

  
   
Resources:
# EC2 Launch Configuration
  WebAppLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      KeyName: !Ref EC2AccessKeyPair
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt-get update -y
          apt-get install unzip awscli -y
          apt-get install apache2 -y
          systemctl start apache2.service
          cd /var/www/html
          aws s3 cp s3://udacity-demo-1/udacity.zip .
          unzip -o udacity.zip
      ImageId: ami-07e6faad15db3b345 # Need to change this to Ubuntu 18
      IamInstanceProfile: !Ref EC2InstanceProfileRole
      SecurityGroups:
      - Fn::ImportValue: 
          !Sub "${ProjectName}-WebSecurityGroupID"
      InstanceType: t2.medium
      BlockDeviceMappings:
      - DeviceName: "/dev/sdk"
        Ebs:
          VolumeSize: '10'
  
  # AutoScaling Group        
  WebAppGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      # A list of subnet IDs for a virtual private cloud (VPC)
      VPCZoneIdentifier: [subnet-0d9b8ade4891a0c11]
        # Fn::ImportValue: !Sub "UdacityProject2-Public-Subnet-1-CIDR"
        # Fn::Join: ['', [ '[' , Fn::ImportValue: !Sub '${ProjectName}-Public-Subnet-CIDRs', ']']]
      LaunchConfigurationName: !Ref WebAppLaunchConfig
      MinSize: '2'
      MaxSize: '6'
      #TargetGroupARNs:
      #- Ref: WebAppTargetGroup
  
  WebAppLB:
    Type: AWS::ElasticLoadBalancingV2:LoadBalancer
    Properties:
      Subnets:
      - Fn::ImportValue: !Sub "Public Subnet 1"
      - Fn::ImportValue: !Sub "Public Subnet 2"
      SecurityGroups:
      - Ref: LBSecGroup
    
  Listener:
    Type: AWS::ElasticLoadBalancingV2:Listener
    Properties:
      DefaultActions:
      - Type: forward
      TargetGroupArn:
        Ref: WebAppTargetGroup
      LoadBalancerArn:
        Ref: WebAppLB
      Port: '80'
      Protocol: HTTP
  
  ALBListnerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
      - Type: forward
        TargetGroupArn: !Ref 'WebAppTargetGroup'
        Conditions:
        - Field: path-pattern
          Values: [/]
        ListenerArn: !Ref 'Listner'
        Priority: 1

  WebAppTargetGroup:
  ## Checks for an HTTP response
    Type: AWS::ElasticLoadBalancingV2::TargetGroup # Property of an autoscaling group
    Properties:
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: / # Filepath of what you want to check.
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 8
      HealthyThresholdCount: 2
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 5
      VpcId:
        Fn::ImportValue:
          Fn::Sub: "${ProjectName}-VPCID"


